# Generated by Django 5.0.6 on 2026-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_seed_from_whatsapp_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectedaccount",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
    ]
