# Generated by Django 5.0.6 on 2026-05-11 22:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the customer issue",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("webchat", "Web Chat"),
                            ("instagram", "Instagram"),
                        ],
                        help_text="Communication channel where the ticket originated",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        help_text="Current ticket status in the support workflow",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level affecting SLA and routing",
                        max_length=20,
                    ),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this ticket's SLA expires (for escalation)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible storage for AI context, automation data, and integrations",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent currently responsible for this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who created this support ticket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="crm.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Ticket",
                "verbose_name_plural": "Support Tickets",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "Human Agent"),
                            ("system", "System"),
                            ("ai_agent", "AI Agent"),
                        ],
                        help_text="Type of sender (customer, agent, system, AI)",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        help_text="Message direction (inbound/outbound)",
                        max_length=20,
                    ),
                ),
                (
                    "sender_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the sender (User ID, Customer ID, AI Agent ID, etc.)",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual message content/text"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an internal note not visible to customers",
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID from external platform (WhatsApp, email provider, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI context, automation data, attachments, rich content, etc.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Ticket this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="helpdesk.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "status"], name="helpdesk_ticket_org_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "priority"], name="helpdesk_ticket_org_priority"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "channel"], name="helpdesk_ticket_org_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "assigned_to"],
                name="helpdesk_ticket_org_assigned",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "sla_due_at"], name="helpdesk_ticket_org_sla"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["customer", "created_at"], name="helpdesk_ticket_cust_created"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "created_at"],
                name="helpdesk_ticket_org_created",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["ticket", "created_at"], name="helpdesk_msg_ticket_created"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "created_at"], name="helpdesk_msg_org_created"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "sender_type"], name="helpdesk_msg_org_sender"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["external_message_id"], name="helpdesk_msg_external_id"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "sender_id", "created_at"],
                name="helpdesk_msg_sender_created",
            ),
        ),
    ]
