# Generated by Django 5.0.6 on 2026-05-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="correlation_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Trace id for outbound pipeline and webhooks",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                help_text="Outbound delivery lifecycle; null for inbound-only messages",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="provider_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="WhatsApp Cloud API message id (wamid) after send",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "provider_message_id"],
                name="helpdesk_msg_org_provider_id",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "delivery_status"],
                name="helpdesk_msg_org_delivery",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_message_id__isnull", False)),
                fields=("organization", "provider_message_id"),
                name="helpdesk_msg_org_provider_msg_unique",
            ),
        ),
    ]
