# Generated by Django 5.0.6 on 2026-05-11 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Organization this audit log belongs to",
                        null=True,
                    ),
                ),
                (
                    "actor_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User who performed the action",
                        null=True,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        default="user",
                        help_text="Type of actor (user, system, api_key, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action that was performed (e.g., 'create', 'update', 'delete')",
                        max_length=100,
                    ),
                ),
                (
                    "action_category",
                    models.CharField(
                        blank=True,
                        help_text="Category of action (e.g., 'auth', 'data', 'admin')",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of entity acted upon (model name)",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the entity acted upon",
                        null=True,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name of the entity",
                        max_length=255,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID to correlate related actions within a request or workflow",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User agent string from the request",
                        max_length=500,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, help_text="Session ID if applicable", max_length=100
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("error", "Error"),
                            ("denied", "Access Denied"),
                        ],
                        default="success",
                        help_text="Outcome of the action",
                        max_length=20,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code if applicable",
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Changes made (before/after values for updates)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the operation in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=0,
                        help_text="Risk score for the action (0-100, higher is riskier)",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this action involves sensitive data",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "created_at"],
                        name="audit_logs_organiz_af0d8d_idx",
                    ),
                    models.Index(
                        fields=["actor_user_id", "created_at"],
                        name="audit_logs_actor_u_b024de_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_logs_entity__d4c2e5_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="audit_logs_correla_953e51_idx"
                    ),
                    models.Index(
                        fields=["outcome", "created_at"],
                        name="audit_logs_outcome_b9d3d0_idx",
                    ),
                    models.Index(
                        fields=["risk_score", "created_at"],
                        name="audit_logs_risk_sc_e706f0_idx",
                    ),
                    models.Index(
                        fields=["is_sensitive", "created_at"],
                        name="audit_logs_is_sens_dcb731_idx",
                    ),
                    models.Index(
                        fields=["action_category", "created_at"],
                        name="audit_logs_action__c93035_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="audit_logs_ip_addr_b969fa_idx",
                    ),
                ],
            },
        ),
    ]
