# Generated by Django 5.0.6 on 2026-05-11 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name (e.g., 'Acme Corporation')",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe version of organization name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for the organization (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Organization description"),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        help_text="Primary admin email for the organization",
                        max_length=254,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Organization website URL"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Organization phone number", max_length=20
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Street address", max_length=255
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, help_text="Apartment, suite, etc.", max_length=255
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "state_province",
                    models.CharField(
                        blank=True, help_text="State or Province", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal or ZIP code", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, help_text="Country", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                            ("inactive", "Inactive"),
                        ],
                        default="trial",
                        help_text="Current organization status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the organization is active"
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        help_text="Current subscription tier",
                        max_length=20,
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, help_text="When the trial period ends", null=True
                    ),
                ),
                (
                    "email_domains",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of email domains for auto-assignment (e.g., 'acme.com,acme.org')",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Organization-specific feature flags and settings",
                    ),
                ),
                (
                    "limits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Usage limits for the organization (users, storage, etc.)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional organization metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="organizatio_slug_5b8b37_idx"),
                    models.Index(
                        fields=["status", "is_active"],
                        name="organizatio_status_984885_idx",
                    ),
                    models.Index(
                        fields=["subscription_tier"],
                        name="organizatio_subscri_674973_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="organizatio_created_8a4b5e_idx"
                    ),
                ],
            },
        ),
    ]
